name: Deploy to production

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build image
    uses: Informasjonsforvaltning/workflows/.github/workflows/build-push.yaml@main
    with:
      app_name: simplified-onboarding
      environment: prod
      build_env: true
      build_env_name: BINARY
      build_env_value: simplified-onboarding
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GCP_SA_DIGDIR_FDK_GCR_KEY: ${{ secrets.GCP_SA_DIGDIR_FDK_GCR_KEY }}
  deploy:
    name: Deploy to prod environment with reusable workflow
    needs: [build]
    uses: Informasjonsforvaltning/workflows/.github/workflows/kustomize-deploy.yaml@main
    with:
      app_name: simplified-onboarding
      environment: prod
      cluster: digdir-fdk-prod
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DIGDIR_FDK_AUTODEPLOY: ${{ secrets.DIGDIR_FDK_PROD_AUTODEPLOY }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
